package model

// Action is the semantic meaning of a keyboard binding.
type Action string

const (
	ActionNone            Action = ""
	ActionQuit            Action = "quit"
	ActionRedraw          Action = "redraw"
	ActionNextSection     Action = "next_section"
	ActionPrevSection     Action = "prev_section"
	ActionShowDashboard   Action = "show_dashboard"
	ActionShowSettings    Action = "show_settings"
	ActionShowLedger      Action = "show_ledger"
	ActionShowJournal     Action = "show_journal"
	ActionShowQuests      Action = "show_quests"
	ActionShowLoot        Action = "show_loot"
	ActionShowAssets      Action = "show_assets"
	ActionTransfer        Action = "transfer"
	ActionMoveUp          Action = "move_up"
	ActionMoveDown        Action = "move_down"
	ActionPageUp          Action = "page_up"
	ActionPageDown        Action = "page_down"
	ActionMoveTop         Action = "move_top"
	ActionMoveBottom      Action = "move_bottom"
	ActionEdit            Action = "edit"
	ActionDelete          Action = "delete"
	ActionToggle          Action = "toggle"
	ActionReverse         Action = "reverse"
	ActionCollect         Action = "collect"
	ActionWriteOff        Action = "write_off"
	ActionAppraise        Action = "appraise"
	ActionRecognize       Action = "recognize"
	ActionSell            Action = "sell"
	ActionNewExpense      Action = "new_expense"
	ActionNewIncome       Action = "new_income"
	ActionNewCustom       Action = "new_custom"
	ActionEditTemplate    Action = "edit_template"
	ActionExecuteTemplate Action = "execute_template"
	ActionSubmitCompose   Action = "submit_compose"
	ActionConfirm         Action = "confirm"
	ActionShowCodex       Action = "show_codex"
	ActionShowNotes       Action = "show_notes"
	ActionShowCompendium  Action = "show_compendium"
	ActionSyncCompendium  Action = "sync_compendium"
	ActionSwitchCampaign  Action = "switch_campaign"
	ActionHelp            Action = "help"
	ActionSearch          Action = "search"
	ActionExportCSV       Action = "export_csv"
	ActionExportExcel     Action = "export_excel"
	ActionExportPDF       Action = "export_pdf"
)
