.TH LOOTSHEET-ACCOUNT-DEACTIVATE 1 "Mar 2026" "LootSheet" "LootSheet Manual"
.SH NAME
lootsheet-account-deactivate \\- Deactivate an account
.SH SYNOPSIS
lootsheet account deactivate [flags]
.SH DESCRIPTION
LootSheet CLI

Usage:
  lootsheet account deactivate --code CODE

Example:
  lootsheet account deactivate --code 5120
.SH OPTIONS
.TP
--code=string
account code (default: )
.TP
-h, --help
help for deactivate
.SH SEE ALSO
lootsheet-account(1)
