.TH LOOTSHEET-QUEST-LIST 1 "Mar 2026" "LootSheet" "LootSheet Manual"
.SH NAME
lootsheet-quest-list \\- List quest register entries
.SH SYNOPSIS
lootsheet quest list [flags]
.SH DESCRIPTION
LootSheet CLI

Usage:
  lootsheet quest list

Shows quest status, promised reward, and title for the quest register.
.SH OPTIONS
.TP
-h, --help
help for list
.SH SEE ALSO
lootsheet-quest(1)
