.TH LOOTSHEET-ACCOUNT-RENAME 1 "Mar 2026" "LootSheet" "LootSheet Manual"
.SH NAME
lootsheet-account-rename \\- Rename an existing account
.SH SYNOPSIS
lootsheet account rename [flags]
.SH DESCRIPTION
LootSheet CLI

Usage:
  lootsheet account rename --code CODE --name NAME

Example:
  lootsheet account rename --code 5120 --name "Wizard Ink & Paper"
.SH OPTIONS
.TP
--code=string
account code (default: )
.TP
-h, --help
help for rename
.TP
--name=string
new account name (default: )
.SH SEE ALSO
lootsheet-account(1)
