.TH LOOTSHEET-ACCOUNT-ACTIVATE 1 "Mar 2026" "LootSheet" "LootSheet Manual"
.SH NAME
lootsheet-account-activate \\- Activate an account
.SH SYNOPSIS
lootsheet account activate [flags]
.SH DESCRIPTION
LootSheet CLI

Usage:
  lootsheet account activate --code CODE

Example:
  lootsheet account activate --code 5120
.SH OPTIONS
.TP
--code=string
account code (default: )
.TP
-h, --help
help for activate
.SH SEE ALSO
lootsheet-account(1)
