.TH LOOTSHEET-ACCOUNT-CREATE 1 "Mar 2026" "LootSheet" "LootSheet Manual"
.SH NAME
lootsheet-account-create \\- Create a new account
.SH SYNOPSIS
lootsheet account create [flags]
.SH DESCRIPTION
LootSheet CLI

Usage:
  lootsheet account create --code CODE --name NAME --type TYPE

Types:
  asset
  liability
  equity
  income
  expense

Examples:
  lootsheet account create --code 5120 --name "Wizard Magic Ink" --type expense
  lootsheet account create --code 1210 --name "Dragon Bond Deposits" --type asset
.SH OPTIONS
.TP
--code=string
account code (default: )
.TP
-h, --help
help for create
.TP
--name=string
account name (default: )
.TP
--type=string
account type (asset, liability, equity, income, expense) (default: )
.SH SEE ALSO
lootsheet-account(1)
