.TH LOOTSHEET-ACCOUNT 1 "Mar 2026" "LootSheet" "LootSheet Manual"
.SH NAME
lootsheet-account \\- Manage chart-of-accounts records
.SH SYNOPSIS
lootsheet account [flags]
.SH DESCRIPTION
LootSheet CLI

Usage:
  lootsheet account list
  lootsheet account create --code CODE --name NAME --type TYPE
  lootsheet account rename --code CODE --name NAME
  lootsheet account deactivate --code CODE
  lootsheet account activate --code CODE
  lootsheet account delete --code CODE
  lootsheet account ledger --code CODE

Subcommands:
  list        show the chart of accounts
  create      add a new account to the chart
  rename      change an account name without changing its immutable code
  deactivate  mark an account inactive without deleting history
  activate    reactivate an inactive account
  delete      remove an unused account that has no postings
  ledger      print the posting history for a single account
.SH OPTIONS
.TP
-h, --help
help for account
.SH SEE ALSO
lootsheet(1)
lootsheet-account-activate(1)
lootsheet-account-create(1)
lootsheet-account-deactivate(1)
lootsheet-account-delete(1)
lootsheet-account-ledger(1)
lootsheet-account-list(1)
lootsheet-account-rename(1)
