.TH LOOTSHEET-QUEST-ACCEPT 1 "Mar 2026" "LootSheet" "LootSheet Manual"
.SH NAME
lootsheet-quest-accept \\- Mark an offered quest as accepted
.SH SYNOPSIS
lootsheet quest accept [flags]
.SH DESCRIPTION
LootSheet CLI

Usage:
  lootsheet quest accept --id ID --date YYYY-MM-DD

Example:
  lootsheet quest accept --id quest-123 --date 2026-03-08
.SH OPTIONS
.TP
--date=string
accepted date in YYYY-MM-DD (required) (default: )
.TP
-h, --help
help for accept
.TP
--id=string
quest ID (required) (default: )
.SH SEE ALSO
lootsheet-quest(1)
