.TH LOOTSHEET-ACCOUNT-LEDGER 1 "Mar 2026" "LootSheet" "LootSheet Manual"
.SH NAME
lootsheet-account-ledger \\- Show a single-account ledger report
.SH SYNOPSIS
lootsheet account ledger [flags]
.SH DESCRIPTION
LootSheet CLI

Usage:
  lootsheet account ledger --code CODE

Examples:
  lootsheet account ledger --code 1000
  lootsheet account ledger --code 5100
.SH OPTIONS
.TP
--code=string
account code (default: )
.TP
-h, --help
help for ledger
.SH SEE ALSO
lootsheet-account(1)
