.TH LOOTSHEET-NOTES-LIST 1 "Mar 2026" "LootSheet" "LootSheet Manual"
.SH NAME
lootsheet-notes-list \\- List all notes
.SH SYNOPSIS
lootsheet notes list [flags]
.SH DESCRIPTION
LootSheet CLI

Subcommand: notes list

List all notes, ordered by most recently updated first.

Examples:
  lootsheet notes list
.SH OPTIONS
.TP
-h, --help
help for list
.SH SEE ALSO
lootsheet-notes(1)
